version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: sentinel-v2-dev-central
        LoadBalancerInfo:
          ContainerName: "central"
          ContainerPort: 8100
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-00d4c1a2055c8c836
              - subnet-0b9287d15a18707da
            SecurityGroups:
              - sg-01bb5d1995e4ace3f
            AssignPublicIp: "ENABLED"

Hooks:
  # Pre-deployment validation
  - BeforeInstall: "arn:aws:lambda:us-east-1:590183890857:function:codedeploy-before-install-hook"
  
  # After new tasks are created but before receiving traffic
  - AfterInstall: "arn:aws:lambda:us-east-1:590183890857:function:codedeploy-after-install-hook"
  
  # After test traffic (10%) is routed
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:590183890857:function:codedeploy-after-test-traffic-hook"
  
  # Before shifting all traffic to new deployment
  - BeforeAllowTraffic: "arn:aws:lambda:us-east-1:590183890857:function:codedeploy-before-allow-traffic-hook"
  
  # After all traffic is shifted to new deployment
  - AfterAllowTraffic: "arn:aws:lambda:us-east-1:590183890857:function:codedeploy-after-allow-traffic-hook"
